# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ionic-sim-2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ionic-sim-2
  pod "GCDWebServer", "~> 3.0"

  target 'ionic-sim-2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ionic-sim-2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
